before_script:
  - npm install -g grunt-cli
  - npm install
  - git submodule init
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cp config/config.travis.js config/config.js
  - cp public/js/lib/bootstrap-material-design/less/_variables.less config/_variables.less
  - cd ./extensions/keplergl/browser
  - rm ./package-lock.json
  - ls
  - npm install
  - cd ../../..
  - cd public/js/lib/bootstrap-material-design
  - npm install
  - cd ../../../..
  - grunt production
language: node_js
node_js:
  - "8"
branches:
  only:
  - master
  - develop
  - testing
